/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BringMeRouteImport } from './routes/bring-me'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as FlaggedRouteImport } from './routes/flagged'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LotRouteImport } from './routes/lot'
import { Route as ParkRouteImport } from './routes/park'
import { Route as ParkRequestRouteImport } from './routes/park-request'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as PickupRouteImport } from './routes/pickup'
import { Route as PickupNewRouteImport } from './routes/pickup-new'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WashRouteImport } from './routes/wash'
import { Route as ArriveSlugRouteImport } from './routes/arrive.$slug'
import { Route as LlegarSlugRouteImport } from './routes/llegar.$slug'
import { Route as ThreadThreadIdRouteImport } from './routes/thread.$threadId'
import { Route as ApiPublicAvatarIdRouteImport } from './routes/api/public/avatar/$id'
import { Route as ApiPublicHooksMilestoneRouteImport } from './routes/api/public/hooks/milestone'
import { Route as ApiPublicHooksStaleCarsRouteImport } from './routes/api/public/hooks/stale-cars'
import { Route as ApiPublicHooksUnclaimedReminderRouteImport } from './routes/api/public/hooks/unclaimed-reminder'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BringMeRoute = BringMeRouteImport.update({
  id: '/bring-me',
  path: '/bring-me',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const FlaggedRoute = FlaggedRouteImport.update({
  id: '/flagged',
  path: '/flagged',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LotRoute = LotRouteImport.update({
  id: '/lot',
  path: '/lot',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkRoute = ParkRouteImport.update({
  id: '/park',
  path: '/park',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkRequestRoute = ParkRequestRouteImport.update({
  id: '/park-request',
  path: '/park-request',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupRoute = PickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupNewRoute = PickupNewRouteImport.update({
  id: '/pickup-new',
  path: '/pickup-new',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WashRoute = WashRouteImport.update({
  id: '/wash',
  path: '/wash',
  getParentRoute: () => rootRouteImport,
} as any)
const ArriveSlugRoute = ArriveSlugRouteImport.update({
  id: '/arrive/$slug',
  path: '/arrive/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LlegarSlugRoute = LlegarSlugRouteImport.update({
  id: '/llegar/$slug',
  path: '/llegar/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadThreadIdRoute = ThreadThreadIdRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvatarIdRoute = ApiPublicAvatarIdRouteImport.update({
  id: '/api/public/avatar/$id',
  path: '/api/public/avatar/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksMilestoneRoute = ApiPublicHooksMilestoneRouteImport.update({
  id: '/api/public/hooks/milestone',
  path: '/api/public/hooks/milestone',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksStaleCarsRoute = ApiPublicHooksStaleCarsRouteImport.update({
  id: '/api/public/hooks/stale-cars',
  path: '/api/public/hooks/stale-cars',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksUnclaimedReminderRoute =
  ApiPublicHooksUnclaimedReminderRouteImport.update({
    id: '/api/public/hooks/unclaimed-reminder',
    path: '/api/public/hooks/unclaimed-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bring-me': typeof BringMeRoute
  '/compose': typeof ComposeRoute
  '/flagged': typeof FlaggedRoute
  '/inbox': typeof InboxRoute
  '/lot': typeof LotRoute
  '/park': typeof ParkRoute
  '/park-request': typeof ParkRequestRoute
  '/parts': typeof PartsRoute
  '/pickup': typeof PickupRoute
  '/pickup-new': typeof PickupNewRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/wash': typeof WashRoute
  '/arrive/$slug': typeof ArriveSlugRoute
  '/llegar/$slug': typeof LlegarSlugRoute
  '/thread/$threadId': typeof ThreadThreadIdRoute
  '/api/public/avatar/$id': typeof ApiPublicAvatarIdRoute
  '/api/public/hooks/milestone': typeof ApiPublicHooksMilestoneRoute
  '/api/public/hooks/stale-cars': typeof ApiPublicHooksStaleCarsRoute
  '/api/public/hooks/unclaimed-reminder': typeof ApiPublicHooksUnclaimedReminderRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bring-me': typeof BringMeRoute
  '/compose': typeof ComposeRoute
  '/flagged': typeof FlaggedRoute
  '/inbox': typeof InboxRoute
  '/lot': typeof LotRoute
  '/park': typeof ParkRoute
  '/park-request': typeof ParkRequestRoute
  '/parts': typeof PartsRoute
  '/pickup': typeof PickupRoute
  '/pickup-new': typeof PickupNewRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/wash': typeof WashRoute
  '/arrive/$slug': typeof ArriveSlugRoute
  '/llegar/$slug': typeof LlegarSlugRoute
  '/thread/$threadId': typeof ThreadThreadIdRoute
  '/api/public/avatar/$id': typeof ApiPublicAvatarIdRoute
  '/api/public/hooks/milestone': typeof ApiPublicHooksMilestoneRoute
  '/api/public/hooks/stale-cars': typeof ApiPublicHooksStaleCarsRoute
  '/api/public/hooks/unclaimed-reminder': typeof ApiPublicHooksUnclaimedReminderRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/bring-me': typeof BringMeRoute
  '/compose': typeof ComposeRoute
  '/flagged': typeof FlaggedRoute
  '/inbox': typeof InboxRoute
  '/lot': typeof LotRoute
  '/park': typeof ParkRoute
  '/park-request': typeof ParkRequestRoute
  '/parts': typeof PartsRoute
  '/pickup': typeof PickupRoute
  '/pickup-new': typeof PickupNewRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/terms': typeof TermsRoute
  '/wash': typeof WashRoute
  '/arrive/$slug': typeof ArriveSlugRoute
  '/llegar/$slug': typeof LlegarSlugRoute
  '/thread/$threadId': typeof ThreadThreadIdRoute
  '/api/public/avatar/$id': typeof ApiPublicAvatarIdRoute
  '/api/public/hooks/milestone': typeof ApiPublicHooksMilestoneRoute
  '/api/public/hooks/stale-cars': typeof ApiPublicHooksStaleCarsRoute
  '/api/public/hooks/unclaimed-reminder': typeof ApiPublicHooksUnclaimedReminderRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/bring-me'
    | '/compose'
    | '/flagged'
    | '/inbox'
    | '/lot'
    | '/park'
    | '/park-request'
    | '/parts'
    | '/pickup'
    | '/pickup-new'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/wash'
    | '/arrive/$slug'
    | '/llegar/$slug'
    | '/thread/$threadId'
    | '/api/public/avatar/$id'
    | '/api/public/hooks/milestone'
    | '/api/public/hooks/stale-cars'
    | '/api/public/hooks/unclaimed-reminder'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/bring-me'
    | '/compose'
    | '/flagged'
    | '/inbox'
    | '/lot'
    | '/park'
    | '/park-request'
    | '/parts'
    | '/pickup'
    | '/pickup-new'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/wash'
    | '/arrive/$slug'
    | '/llegar/$slug'
    | '/thread/$threadId'
    | '/api/public/avatar/$id'
    | '/api/public/hooks/milestone'
    | '/api/public/hooks/stale-cars'
    | '/api/public/hooks/unclaimed-reminder'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/bring-me'
    | '/compose'
    | '/flagged'
    | '/inbox'
    | '/lot'
    | '/park'
    | '/park-request'
    | '/parts'
    | '/pickup'
    | '/pickup-new'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/reset-password'
    | '/settings'
    | '/terms'
    | '/wash'
    | '/arrive/$slug'
    | '/llegar/$slug'
    | '/thread/$threadId'
    | '/api/public/avatar/$id'
    | '/api/public/hooks/milestone'
    | '/api/public/hooks/stale-cars'
    | '/api/public/hooks/unclaimed-reminder'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BringMeRoute: typeof BringMeRoute
  ComposeRoute: typeof ComposeRoute
  FlaggedRoute: typeof FlaggedRoute
  InboxRoute: typeof InboxRoute
  LotRoute: typeof LotRoute
  ParkRoute: typeof ParkRoute
  ParkRequestRoute: typeof ParkRequestRoute
  PartsRoute: typeof PartsRoute
  PickupRoute: typeof PickupRoute
  PickupNewRoute: typeof PickupNewRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  TermsRoute: typeof TermsRoute
  WashRoute: typeof WashRoute
  ArriveSlugRoute: typeof ArriveSlugRoute
  LlegarSlugRoute: typeof LlegarSlugRoute
  ThreadThreadIdRoute: typeof ThreadThreadIdRoute
  ApiPublicAvatarIdRoute: typeof ApiPublicAvatarIdRoute
  ApiPublicHooksMilestoneRoute: typeof ApiPublicHooksMilestoneRoute
  ApiPublicHooksStaleCarsRoute: typeof ApiPublicHooksStaleCarsRoute
  ApiPublicHooksUnclaimedReminderRoute: typeof ApiPublicHooksUnclaimedReminderRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bring-me': {
      id: '/bring-me'
      path: '/bring-me'
      fullPath: '/bring-me'
      preLoaderRoute: typeof BringMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flagged': {
      id: '/flagged'
      path: '/flagged'
      fullPath: '/flagged'
      preLoaderRoute: typeof FlaggedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lot': {
      id: '/lot'
      path: '/lot'
      fullPath: '/lot'
      preLoaderRoute: typeof LotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/park': {
      id: '/park'
      path: '/park'
      fullPath: '/park'
      preLoaderRoute: typeof ParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/park-request': {
      id: '/park-request'
      path: '/park-request'
      fullPath: '/park-request'
      preLoaderRoute: typeof ParkRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup': {
      id: '/pickup'
      path: '/pickup'
      fullPath: '/pickup'
      preLoaderRoute: typeof PickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup-new': {
      id: '/pickup-new'
      path: '/pickup-new'
      fullPath: '/pickup-new'
      preLoaderRoute: typeof PickupNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wash': {
      id: '/wash'
      path: '/wash'
      fullPath: '/wash'
      preLoaderRoute: typeof WashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrive/$slug': {
      id: '/arrive/$slug'
      path: '/arrive/$slug'
      fullPath: '/arrive/$slug'
      preLoaderRoute: typeof ArriveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llegar/$slug': {
      id: '/llegar/$slug'
      path: '/llegar/$slug'
      fullPath: '/llegar/$slug'
      preLoaderRoute: typeof LlegarSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/$threadId': {
      id: '/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/thread/$threadId'
      preLoaderRoute: typeof ThreadThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/avatar/$id': {
      id: '/api/public/avatar/$id'
      path: '/api/public/avatar/$id'
      fullPath: '/api/public/avatar/$id'
      preLoaderRoute: typeof ApiPublicAvatarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/milestone': {
      id: '/api/public/hooks/milestone'
      path: '/api/public/hooks/milestone'
      fullPath: '/api/public/hooks/milestone'
      preLoaderRoute: typeof ApiPublicHooksMilestoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/stale-cars': {
      id: '/api/public/hooks/stale-cars'
      path: '/api/public/hooks/stale-cars'
      fullPath: '/api/public/hooks/stale-cars'
      preLoaderRoute: typeof ApiPublicHooksStaleCarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/unclaimed-reminder': {
      id: '/api/public/hooks/unclaimed-reminder'
      path: '/api/public/hooks/unclaimed-reminder'
      fullPath: '/api/public/hooks/unclaimed-reminder'
      preLoaderRoute: typeof ApiPublicHooksUnclaimedReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BringMeRoute: BringMeRoute,
  ComposeRoute: ComposeRoute,
  FlaggedRoute: FlaggedRoute,
  InboxRoute: InboxRoute,
  LotRoute: LotRoute,
  ParkRoute: ParkRoute,
  ParkRequestRoute: ParkRequestRoute,
  PartsRoute: PartsRoute,
  PickupRoute: PickupRoute,
  PickupNewRoute: PickupNewRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  TermsRoute: TermsRoute,
  WashRoute: WashRoute,
  ArriveSlugRoute: ArriveSlugRoute,
  LlegarSlugRoute: LlegarSlugRoute,
  ThreadThreadIdRoute: ThreadThreadIdRoute,
  ApiPublicAvatarIdRoute: ApiPublicAvatarIdRoute,
  ApiPublicHooksMilestoneRoute: ApiPublicHooksMilestoneRoute,
  ApiPublicHooksStaleCarsRoute: ApiPublicHooksStaleCarsRoute,
  ApiPublicHooksUnclaimedReminderRoute: ApiPublicHooksUnclaimedReminderRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
