/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PickupNewRouteImport } from './routes/pickup-new'
import { Route as PickupRouteImport } from './routes/pickup'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as ParkRouteImport } from './routes/park'
import { Route as LotRouteImport } from './routes/lot'
import { Route as ComposeRouteImport } from './routes/compose'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadThreadIdRouteImport } from './routes/thread.$threadId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupNewRoute = PickupNewRouteImport.update({
  id: '/pickup-new',
  path: '/pickup-new',
  getParentRoute: () => rootRouteImport,
} as any)
const PickupRoute = PickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkRoute = ParkRouteImport.update({
  id: '/park',
  path: '/park',
  getParentRoute: () => rootRouteImport,
} as any)
const LotRoute = LotRouteImport.update({
  id: '/lot',
  path: '/lot',
  getParentRoute: () => rootRouteImport,
} as any)
const ComposeRoute = ComposeRouteImport.update({
  id: '/compose',
  path: '/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadThreadIdRoute = ThreadThreadIdRouteImport.update({
  id: '/thread/$threadId',
  path: '/thread/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compose': typeof ComposeRoute
  '/lot': typeof LotRoute
  '/park': typeof ParkRoute
  '/parts': typeof PartsRoute
  '/pickup': typeof PickupRoute
  '/pickup-new': typeof PickupNewRoute
  '/profile': typeof ProfileRoute
  '/thread/$threadId': typeof ThreadThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compose': typeof ComposeRoute
  '/lot': typeof LotRoute
  '/park': typeof ParkRoute
  '/parts': typeof PartsRoute
  '/pickup': typeof PickupRoute
  '/pickup-new': typeof PickupNewRoute
  '/profile': typeof ProfileRoute
  '/thread/$threadId': typeof ThreadThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/compose': typeof ComposeRoute
  '/lot': typeof LotRoute
  '/park': typeof ParkRoute
  '/parts': typeof PartsRoute
  '/pickup': typeof PickupRoute
  '/pickup-new': typeof PickupNewRoute
  '/profile': typeof ProfileRoute
  '/thread/$threadId': typeof ThreadThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/compose'
    | '/lot'
    | '/park'
    | '/parts'
    | '/pickup'
    | '/pickup-new'
    | '/profile'
    | '/thread/$threadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/compose'
    | '/lot'
    | '/park'
    | '/parts'
    | '/pickup'
    | '/pickup-new'
    | '/profile'
    | '/thread/$threadId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/compose'
    | '/lot'
    | '/park'
    | '/parts'
    | '/pickup'
    | '/pickup-new'
    | '/profile'
    | '/thread/$threadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComposeRoute: typeof ComposeRoute
  LotRoute: typeof LotRoute
  ParkRoute: typeof ParkRoute
  PartsRoute: typeof PartsRoute
  PickupRoute: typeof PickupRoute
  PickupNewRoute: typeof PickupNewRoute
  ProfileRoute: typeof ProfileRoute
  ThreadThreadIdRoute: typeof ThreadThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup-new': {
      id: '/pickup-new'
      path: '/pickup-new'
      fullPath: '/pickup-new'
      preLoaderRoute: typeof PickupNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pickup': {
      id: '/pickup'
      path: '/pickup'
      fullPath: '/pickup'
      preLoaderRoute: typeof PickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/park': {
      id: '/park'
      path: '/park'
      fullPath: '/park'
      preLoaderRoute: typeof ParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lot': {
      id: '/lot'
      path: '/lot'
      fullPath: '/lot'
      preLoaderRoute: typeof LotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compose': {
      id: '/compose'
      path: '/compose'
      fullPath: '/compose'
      preLoaderRoute: typeof ComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/$threadId': {
      id: '/thread/$threadId'
      path: '/thread/$threadId'
      fullPath: '/thread/$threadId'
      preLoaderRoute: typeof ThreadThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComposeRoute: ComposeRoute,
  LotRoute: LotRoute,
  ParkRoute: ParkRoute,
  PartsRoute: PartsRoute,
  PickupRoute: PickupRoute,
  PickupNewRoute: PickupNewRoute,
  ProfileRoute: ProfileRoute,
  ThreadThreadIdRoute: ThreadThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
